sudo: required
language: node_js
node_js:
  - "10"
branches:
  only:
    - dev
before_install:
  - npm install -g @angular/cli
install:
  - npm install
cache:
  directories:
    - "/node_modules"
script:
  - npm run lint
  - npm run test
  - npm run build-prod
